create extension if not exists pgcrypto;
create type user_role as enum('patient','caregiver','clinician','admin');
create type consent_status as enum('active','expired','revoked');
create type summary_status as enum('draft','approved','rejected');
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,role user_role not null,created_at timestamptz default now());
create table if not exists pregnancies(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,gestational_weeks int,due_date date,trimester text,notes text);
create table if not exists care_plans(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,clinician_id uuid references profiles(id),title text not null,clinical_instructions text,caregiver_summary text,warning_signs text,status text default 'approved',ai_generated_summary boolean default false,ai_approved boolean default false);
create table if not exists consents(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,caregiver_id uuid references profiles(id) on delete cascade,permissions jsonb not null default '{}'::jsonb,status consent_status default 'active',starts_at timestamptz default now(),expires_at timestamptz,revoked_at timestamptz);
create table if not exists care_tasks(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,assigned_to uuid references profiles(id),created_by uuid references profiles(id),title text not null,description text,due_at timestamptz,status text default 'pending',completed_at timestamptz);
create table if not exists appointments(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,clinician_id uuid references profiles(id),starts_at timestamptz,title text not null,location text,notes text);
create table if not exists medications(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,clinician_id uuid references profiles(id),name text not null,dosage text,frequency text,scheduled_time text,instructions text,active boolean default true);
create table if not exists observations(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,submitted_by uuid references profiles(id),content text not null,created_at timestamptz default now(),reviewed_at timestamptz,reviewed_by uuid references profiles(id));
create table if not exists clinical_summaries(id uuid primary key default gen_random_uuid(),patient_id uuid references profiles(id) on delete cascade,clinician_id uuid references profiles(id),content text not null,status summary_status default 'draft',ai_generated boolean default true,reviewed_at timestamptz,approved_at timestamptz);
alter table profiles enable row level security;alter table pregnancies enable row level security;alter table care_plans enable row level security;alter table consents enable row level security;alter table care_tasks enable row level security;alter table appointments enable row level security;alter table medications enable row level security;alter table observations enable row level security;alter table clinical_summaries enable row level security;
create or replace function public.has_active_consent(p_patient uuid,p_caregiver uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from consents where patient_id=p_patient and caregiver_id=p_caregiver and status='active' and (expires_at is null or expires_at>now()))$$;
create policy "patient_own_pregnancy" on pregnancies for select using(patient_id=auth.uid());
create policy "patient_own_plan" on care_plans for select using(patient_id=auth.uid());
create policy "caregiver_consented_plan" on care_plans for select using(has_active_consent(patient_id,auth.uid()));
create policy "patient_manage_consent" on consents for all using(patient_id=auth.uid()) with check(patient_id=auth.uid());
create policy "caregiver_read_consent" on consents for select using(caregiver_id=auth.uid());
create policy "patient_tasks" on care_tasks for select using(patient_id=auth.uid());
create policy "caregiver_tasks" on care_tasks for select using(assigned_to=auth.uid() and has_active_consent(patient_id,auth.uid()));
create policy "patient_appointments" on appointments for select using(patient_id=auth.uid());
create policy "caregiver_appointments" on appointments for select using(has_active_consent(patient_id,auth.uid()));
create policy "patient_medications" on medications for select using(patient_id=auth.uid());
create policy "caregiver_medications" on medications for select using(has_active_consent(patient_id,auth.uid()));
create policy "patient_approved_summary" on clinical_summaries for select using(patient_id=auth.uid() and status='approved');
