import { createServer } from 'node:http';
import { mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { loadEnvFile } from 'node:process';

try { loadEnvFile(join(dirname(fileURLToPath(import.meta.url)), '..', '.env')); } catch {}
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DATA_DIR = join(ROOT, 'data');
mkdirSync(DATA_DIR, { recursive: true });
const { DatabaseSync } = await import('node:sqlite');
const db = new DatabaseSync(join(DATA_DIR, 'carebridge.sqlite'));
const hash = (s) => createHash('sha256').update(String(s)).digest('hex');

const DEMO_PASSWORDS = {
  patient: process.env.DEMO_PATIENT_PASSWORD || 'CareBridge@123',
  caregiver: process.env.DEMO_CAREGIVER_PASSWORD || 'CareBridge@123',
  clinician: process.env.DEMO_CLINICIAN_PASSWORD || 'CareBridge@123',
  admin: process.env.DEMO_ADMIN_PASSWORD || 'CareBridge@123',
};

db.exec(`
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS profiles (
 id TEXT PRIMARY KEY, full_name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, phone TEXT,
 role TEXT NOT NULL CHECK(role IN ('patient','caregiver','clinician','admin')), status TEXT NOT NULL DEFAULT 'active', license_number TEXT, specialization TEXT, qualifications TEXT, hospital TEXT, years_experience INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS auth_users (profile_id TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS patients (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id), clinician_id TEXT, date_of_birth TEXT, condition TEXT, gestational_weeks INTEGER DEFAULT 0, due_date TEXT, trimester TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS caregiver_access (
 id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), caregiver_id TEXT NOT NULL REFERENCES profiles(id),
 can_view_care_plan INTEGER NOT NULL DEFAULT 0, can_view_medications INTEGER NOT NULL DEFAULT 0, can_view_tasks INTEGER NOT NULL DEFAULT 0,
 can_view_appointments INTEGER NOT NULL DEFAULT 0, can_view_financials INTEGER NOT NULL DEFAULT 0, can_report_concerns INTEGER NOT NULL DEFAULT 1,
 status TEXT NOT NULL DEFAULT 'active', expires_at TEXT
);
CREATE TABLE IF NOT EXISTS tasks (
 id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), assigned_to TEXT, created_by TEXT NOT NULL, title TEXT NOT NULL,
 description TEXT, priority TEXT NOT NULL DEFAULT 'normal', status TEXT NOT NULL DEFAULT 'pending', due_at TEXT, completed_at TEXT
);
CREATE TABLE IF NOT EXISTS alerts (
 id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), created_by TEXT NOT NULL, assigned_clinician_id TEXT,
 alert_type TEXT NOT NULL, severity TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new',
 acknowledged_by TEXT, acknowledged_at TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS medications (
 id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), clinician_id TEXT NOT NULL, name TEXT NOT NULL, dosage TEXT NOT NULL,
 frequency TEXT NOT NULL, scheduled_time TEXT, instructions TEXT, active INTEGER NOT NULL DEFAULT 1, taken_at TEXT, taken_by TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS appointments (id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), clinician_id TEXT NOT NULL, appointment_date TEXT NOT NULL, appointment_time TEXT NOT NULL, appointment_type TEXT NOT NULL, location TEXT, status TEXT NOT NULL DEFAULT 'scheduled', notes TEXT, caregiver_confirmed INTEGER NOT NULL DEFAULT 0, caregiver_confirmed_at TEXT, caregiver_confirmed_by TEXT);
CREATE TABLE IF NOT EXISTS access_events (id TEXT PRIMARY KEY, actor_id TEXT, patient_id TEXT, caregiver_id TEXT, action TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS care_plans (
 id TEXT PRIMARY KEY, patient_id TEXT UNIQUE NOT NULL REFERENCES patients(id), clinician_id TEXT NOT NULL, title TEXT NOT NULL,
 clinical_instructions TEXT NOT NULL, caregiver_summary TEXT, warning_signs TEXT, status TEXT NOT NULL DEFAULT 'draft',
 ai_generated_summary INTEGER NOT NULL DEFAULT 0, ai_approved INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS registration_requests (
 id TEXT PRIMARY KEY, full_name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, requested_role TEXT NOT NULL,
 message TEXT, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS notifications (
 id TEXT PRIMARY KEY, recipient_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL,
 related_patient_id TEXT, read_at TEXT, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS personal_records (
 patient_id TEXT PRIMARY KEY REFERENCES patients(id) ON DELETE CASCADE,
 full_name TEXT NOT NULL, date_of_birth TEXT, phone TEXT, email TEXT, address TEXT,
 emergency_contact_name TEXT, emergency_contact_phone TEXT, relationship TEXT, updated_by TEXT, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS health_profiles (
 patient_id TEXT PRIMARY KEY REFERENCES patients(id) ON DELETE CASCADE,
 blood_group TEXT, medicine_allergies TEXT, diabetes TEXT, chronic_illnesses TEXT,
 previous_conditions TEXT, surgical_history TEXT, obstetric_history TEXT, current_health_notes TEXT,
 updated_by TEXT, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS vaccinations (
 id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
 vaccine_name TEXT NOT NULL, dose TEXT, administered_date TEXT, next_due_date TEXT,
 status TEXT NOT NULL DEFAULT 'completed', notes TEXT, created_by TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pregnancy_scans (
 id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
 scan_type TEXT NOT NULL, scan_date TEXT, gestational_week INTEGER, findings TEXT, clinician_notes TEXT,
 file_reference TEXT, status TEXT NOT NULL DEFAULT 'available', created_by TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS clinician_availability (
 id TEXT PRIMARY KEY, clinician_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
 availability_date TEXT NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL,
 slot_minutes INTEGER NOT NULL DEFAULT 30, status TEXT NOT NULL DEFAULT 'available', created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS appointment_reschedule_requests (
 id TEXT PRIMARY KEY, appointment_id TEXT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
 requested_by TEXT NOT NULL, requested_date TEXT, requested_time TEXT, reason TEXT,
 status TEXT NOT NULL DEFAULT 'pending', reviewed_by TEXT, reviewed_at TEXT, created_at TEXT NOT NULL
);
`);

for (const sql of [
  `ALTER TABLE profiles ADD COLUMN status TEXT NOT NULL DEFAULT 'active'`,
  `ALTER TABLE profiles ADD COLUMN license_number TEXT`,
  `ALTER TABLE profiles ADD COLUMN specialization TEXT`,
  `ALTER TABLE profiles ADD COLUMN qualifications TEXT`,
  `ALTER TABLE profiles ADD COLUMN hospital TEXT`,
  `ALTER TABLE profiles ADD COLUMN years_experience INTEGER`,
  `ALTER TABLE medications ADD COLUMN taken_at TEXT`,
  `ALTER TABLE medications ADD COLUMN taken_by TEXT`,
  `ALTER TABLE appointments ADD COLUMN caregiver_confirmed INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE appointments ADD COLUMN caregiver_confirmed_at TEXT`,
  `ALTER TABLE appointments ADD COLUMN caregiver_confirmed_by TEXT`,
]) { try { db.exec(sql); } catch {} }

function profile(id, name, email, role, password) {
  db.prepare(`INSERT OR IGNORE INTO profiles(id,full_name,email,role,status) VALUES(?,?,?,?,?)`).run(id,name,email,role,'active');
  db.prepare(`INSERT INTO auth_users(profile_id,password_hash) VALUES(?,?) ON CONFLICT(profile_id) DO UPDATE SET password_hash=excluded.password_hash`).run(id,hash(password));
}
profile('demo-patient-profile','Lakshmi Rao','patient@carebridge.demo','patient',DEMO_PASSWORDS.patient);
profile('demo-caregiver','Anita Kumar','caregiver@carebridge.demo','caregiver',DEMO_PASSWORDS.caregiver);
profile('demo-clinician','Dr. Meera Rao','clinician@carebridge.demo','clinician',DEMO_PASSWORDS.clinician);
profile('demo-admin','CareBridge Admin','admin@carebridge.demo','admin',DEMO_PASSWORDS.admin);
db.prepare(`INSERT OR IGNORE INTO patients(id,profile_id,clinician_id,condition,gestational_weeks,due_date,trimester,notes) VALUES(?,?,?,?,?,?,?,?)`).run('demo-patient','demo-patient-profile','demo-clinician','Pregnancy',28,'2026-12-25','Third trimester','Routine maternity follow-up.');
db.prepare(`INSERT OR IGNORE INTO caregiver_access(id,patient_id,caregiver_id,can_view_care_plan,can_view_medications,can_view_tasks,can_view_appointments,can_report_concerns,status,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run('ca1','demo-patient','demo-caregiver',1,1,1,1,1,'active','2026-11-15T23:59:59+05:30');
const task = db.prepare(`INSERT OR IGNORE INTO tasks(id,patient_id,assigned_to,created_by,title,description,priority,status) VALUES(?,?,?,?,?,?,?,?)`);
task.run('t1','demo-patient','demo-caregiver','demo-clinician','Morning hydration check','Support the morning hydration routine.','normal','completed');
task.run('t2','demo-patient','demo-caregiver','demo-clinician','Prepare for next appointment','Help gather questions and current medication information.','normal','pending');
task.run('t3','demo-patient','demo-caregiver','demo-clinician','Evening wellness check','Complete the evening check-in and record an observation if needed.','high','pending');
const med = db.prepare(`INSERT OR IGNORE INTO medications(id,patient_id,clinician_id,name,dosage,frequency,scheduled_time,instructions,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`);
med.run('m1','demo-patient','demo-clinician','Prenatal supplement','As prescribed','Once daily','08:00','Take as directed by the clinician.',1,new Date().toISOString());
med.run('m2','demo-patient','demo-clinician','Iron supplement','As prescribed','Once daily','20:00','Take as directed by the clinician.',1,new Date().toISOString());
db.prepare(`INSERT OR IGNORE INTO care_plans(id,patient_id,clinician_id,title,clinical_instructions,caregiver_summary,warning_signs,status,ai_generated_summary,ai_approved,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run('cp1','demo-patient','demo-clinician','Maternity Care Plan','Continue prescribed supplements, maintain hydration, follow the agreed nutrition and rest plan, attend scheduled maternity visits, and complete the next recommended check-in.','Support hydration, rest, appointment preparation, and the agreed daily care routine. Follow clinician-approved instructions and report concerns rather than changing clinical instructions.','If there is a significant or concerning change in condition, contact the maternity care team promptly.','approved',0,1,new Date().toISOString());
db.prepare(`INSERT OR IGNORE INTO appointments(id,patient_id,clinician_id,appointment_date,appointment_time,appointment_type,location,status,notes) VALUES(?,?,?,?,?,?,?,?,?)`).run('a1','demo-patient','demo-clinician','2026-10-12','10:30','Routine maternity follow-up','Maternity Care Clinic','scheduled','Bring current medication list and questions.');
db.prepare(`INSERT OR IGNORE INTO personal_records(patient_id,full_name,date_of_birth,phone,email,address,emergency_contact_name,emergency_contact_phone,relationship,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run('demo-patient','Lakshmi Rao','1998-04-18','+91 90000 00000','patient@carebridge.demo','On file','Anita Kumar','+91 91111 11111','Caregiver','demo-clinician',new Date().toISOString());
db.prepare(`INSERT OR IGNORE INTO health_profiles(patient_id,blood_group,medicine_allergies,diabetes,chronic_illnesses,previous_conditions,surgical_history,obstetric_history,current_health_notes,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run('demo-patient','O positive','No known medicine allergies','No','None reported','No significant previous conditions reported','No previous surgery reported','First pregnancy; routine antenatal follow-up','Clinician-maintained private health profile.','demo-clinician',new Date().toISOString());
const vacc=db.prepare(`INSERT OR IGNORE INTO vaccinations(id,patient_id,vaccine_name,dose,administered_date,next_due_date,status,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`);
vacc.run('v1','demo-patient','Tdap','Dose 1','2026-09-10','2026-10-10','completed','Routine antenatal vaccination record.','demo-clinician',new Date().toISOString());
vacc.run('v2','demo-patient','Influenza','Seasonal dose','2026-08-20','','completed','Seasonal influenza vaccination.','demo-clinician',new Date().toISOString());
const scan=db.prepare(`INSERT OR IGNORE INTO pregnancy_scans(id,patient_id,scan_type,scan_date,gestational_week,findings,clinician_notes,file_reference,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`);
scan.run('s1','demo-patient','Dating scan','2026-06-10',12,'Single viable intrauterine pregnancy; measurements consistent with dates.','Reviewed by maternity clinician.','', 'available','demo-clinician',new Date().toISOString());
scan.run('s2','demo-patient','Anomaly scan','2026-07-28',20,'Anatomical survey recorded in the clinical report.','Continue routine antenatal follow-up.','', 'available','demo-clinician',new Date().toISOString());
scan.run('s3','demo-patient','Growth scan','2026-09-22',26,'Growth assessment documented in the clinical record.','Review growth trajectory at next visit.','', 'available','demo-clinician',new Date().toISOString());
const av=db.prepare(`INSERT OR IGNORE INTO clinician_availability(id,clinician_id,availability_date,start_time,end_time,slot_minutes,status,created_at) VALUES(?,?,?,?,?,?,?,?)`);
av.run('av1','demo-clinician','2026-10-12','09:00','13:00',30,'available',new Date().toISOString());
av.run('av2','demo-clinician','2026-10-14','10:00','15:00',30,'available',new Date().toISOString());

const sessions = new Map();
const send = (res,status,body) => { res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization'}); res.end(JSON.stringify(body)); };
async function body(req){let raw='';for await(const c of req)raw+=c;try{return raw?JSON.parse(raw):{}}catch{return {}}}
function auth(req){const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');return token?sessions.get(token):null}
function requireAuth(req,res,roles=[]){const u=auth(req);if(!u){send(res,401,{error:'Not authenticated'});return null}if(roles.length&&!roles.includes(u.role)){send(res,403,{error:'Forbidden'});return null}return u}
const bools=(row,keys)=>{const x={...row};for(const k of keys)x[k]=!!x[k];return x};
const notify=(recipientId,type,title,message,patientId=null)=>{db.prepare(`INSERT INTO notifications(id,recipient_id,type,title,message,related_patient_id,created_at) VALUES(?,?,?,?,?,?,?)`).run(randomUUID(),recipientId,type,title,message,patientId,new Date().toISOString())};
const notifyCareTeam=(patientId,type,title,message)=>{const patient=db.prepare(`SELECT profile_id,clinician_id FROM patients WHERE id=?`).get(patientId);if(!patient)return;notify(patient.profile_id,type,title,message,patientId);const access=db.prepare(`SELECT caregiver_id,can_view_care_plan,can_view_medications,can_view_appointments,status,expires_at FROM caregiver_access WHERE patient_id=? AND status='active'`).get(patientId);if(access){const expired=access.expires_at && new Date(access.expires_at)<new Date();if(!expired)notify(access.caregiver_id,type,title,message,patientId)}if(patient.clinician_id)notify(patient.clinician_id,type,title,message,patientId)};
const createAlert=(b,u)=>{const patientId=b.patient_id||'demo-patient';const assigned=b.assigned_clinician_id||db.prepare(`SELECT clinician_id FROM patients WHERE id=?`).get(patientId)?.clinician_id||'demo-clinician';const id=randomUUID();db.prepare(`INSERT INTO alerts(id,patient_id,created_by,assigned_clinician_id,alert_type,severity,title,message,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,patientId,b.created_by||u.id,assigned,b.alert_type||'caregiver_observation',b.severity||'review',b.title||'Caregiver observation',b.message||'','new',new Date().toISOString());notify(assigned,'caregiver_observation',b.title||'New caregiver observation',b.message||'A caregiver submitted an observation.',patientId);return db.prepare(`SELECT * FROM alerts WHERE id=?`).get(id)};

const server=createServer(async(req,res)=>{
  if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization'});return res.end()}
  const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);
  try {
    if(url.pathname==='/api/health')return send(res,200,{ok:true,database:'sqlite'});
    if(url.pathname==='/api/auth/login'&&req.method==='POST'){
      const b=await body(req);const p=db.prepare(`SELECT p.*,a.password_hash FROM profiles p JOIN auth_users a ON a.profile_id=p.id WHERE lower(p.email)=lower(?)`).get(String(b.email||'').trim());
      if(!p||p.status!=='active'||hash(b.password)!==p.password_hash)return send(res,401,{error:'Invalid email or password'});
      const token=randomBytes(32).toString('hex');sessions.set(token,{id:p.id,full_name:p.full_name,email:p.email,role:p.role});return send(res,200,{token,user:{id:p.id,email:p.email,role:p.role,full_name:p.full_name}});
    }
    if(url.pathname==='/api/auth/me'){const u=requireAuth(req,res);if(!u)return;return send(res,200,{user:u})}
    if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(t)sessions.delete(t);return send(res,200,{ok:true})}
    if(url.pathname==='/api/registration-requests'&&req.method==='POST'){const b=await body(req);if(!b.full_name||!b.email||!['patient','caregiver','clinician'].includes(b.requested_role))return send(res,400,{error:'Name, email and requested role are required'});const id=randomUUID();db.prepare(`INSERT INTO registration_requests(id,full_name,email,phone,requested_role,message,created_at) VALUES(?,?,?,?,?,?,?)`).run(id,b.full_name,b.email,b.phone||'',b.requested_role,b.message||'',new Date().toISOString());return send(res,201,{id,status:'pending'})}
    if(url.pathname==='/api/admin/users'&&req.method==='GET'){const u=requireAuth(req,res,['admin']);if(!u)return;return send(res,200,db.prepare(`SELECT id,full_name,email,phone,role,status,license_number,specialization,qualifications,hospital,years_experience,created_at FROM profiles ORDER BY created_at DESC`).all())}
    if(url.pathname==='/api/admin/registration-requests'&&req.method==='GET'){const u=requireAuth(req,res,['admin']);if(!u)return;return send(res,200,db.prepare(`SELECT * FROM registration_requests ORDER BY created_at DESC`).all())}
    if(url.pathname==='/api/admin/users'&&req.method==='POST'){
      const u=requireAuth(req,res,['admin']);if(!u)return;const b=await body(req);if(!b.full_name||!b.email||!b.password||!['patient','caregiver','clinician'].includes(b.role))return send(res,400,{error:'Name, email, password and role are required'});
      const id=randomUUID();try{db.prepare(`INSERT INTO profiles(id,full_name,email,phone,role,status,license_number,specialization,qualifications,hospital,years_experience) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,b.full_name,b.email,b.phone||'',b.role,'active',b.license_number||null,b.specialization||null,b.qualifications||null,b.hospital||null,b.years_experience?Number(b.years_experience):null);db.prepare(`INSERT INTO auth_users(profile_id,password_hash) VALUES(?,?)`).run(id,hash(b.password));if(b.role==='patient'){const pid=randomUUID();db.prepare(`INSERT INTO patients(id,profile_id,clinician_id,condition,gestational_weeks,due_date,trimester,notes) VALUES(?,?,?,?,?,?,?,?)`).run(pid,id,b.clinician_id||null,'Pregnancy',Number(b.gestational_weeks||0),b.due_date||null,b.trimester||'First trimester',b.notes||'')}return send(res,201,{id,full_name:b.full_name,email:b.email,role:b.role,status:'active'})}catch(e){return send(res,400,{error:e.message.includes('UNIQUE')?'Email already exists':'Unable to create user'})}
    }
    const userMatch=url.pathname.match(/^\/api\/admin\/users\/([^/]+)$/);
    if(userMatch&&req.method==='PATCH'){const u=requireAuth(req,res,['admin']);if(!u)return;const id=userMatch[1],b=await body(req);const fields=['status','full_name','phone','license_number','specialization','qualifications','hospital','years_experience'];const set=fields.filter(k=>b[k]!==undefined).map(k=>`${k}=?`);const vals=fields.filter(k=>b[k]!==undefined).map(k=>k==='years_experience'?Number(b[k]):b[k]);if(set.length)db.prepare(`UPDATE profiles SET ${set.join(',')} WHERE id=?`).run(...vals,id);if(b.password)db.prepare(`UPDATE auth_users SET password_hash=? WHERE profile_id=?`).run(hash(b.password),id);return send(res,200,db.prepare(`SELECT id,full_name,email,phone,role,status,license_number,specialization,qualifications,hospital,years_experience FROM profiles WHERE id=?`).get(id))}
    if(url.pathname==='/api/care-plan'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const patientId=url.searchParams.get('patient_id')||'demo-patient';const row=db.prepare(`SELECT * FROM care_plans WHERE patient_id=?`).get(patientId);return send(res,200,row||null)}
    if(url.pathname==='/api/care-plan'&&req.method==='PUT'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);const patientId=b.patient_id||'demo-patient';const existing=db.prepare(`SELECT id FROM care_plans WHERE patient_id=?`).get(patientId);const now=new Date().toISOString();if(existing)db.prepare(`UPDATE care_plans SET clinician_id=?,title=?,clinical_instructions=?,caregiver_summary=?,warning_signs=?,status=?,ai_generated_summary=?,ai_approved=?,updated_at=? WHERE patient_id=?`).run(u.role==='clinician'?u.id:(b.clinician_id||'demo-clinician'),b.title,b.clinical_instructions,b.caregiver_summary||'',b.warning_signs||'','approved',0,0,now,patientId);else db.prepare(`INSERT INTO care_plans(id,patient_id,clinician_id,title,clinical_instructions,caregiver_summary,warning_signs,status,ai_generated_summary,ai_approved,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(randomUUID(),patientId,u.id,b.title,b.clinical_instructions,b.caregiver_summary||'',b.warning_signs||'','approved',0,0,now);const plan=db.prepare(`SELECT * FROM care_plans WHERE patient_id=?`).get(patientId);const patient=db.prepare(`SELECT profile_id FROM patients WHERE id=?`).get(patientId);notifyCareTeam(patientId,'care_plan','Care plan updated','Your clinician updated the maternity care plan.');return send(res,200,plan)}
    if(url.pathname==='/api/medications'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const patientId=url.searchParams.get('patient_id')||'demo-patient';return send(res,200,db.prepare(`SELECT * FROM medications WHERE patient_id=? ORDER BY active DESC, created_at DESC`).all(patientId).map(x=>({...x,active:!!x.active})))}
    if(url.pathname==='/api/medications'&&req.method==='POST'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);if(!b.name||!b.dosage||!b.frequency)return send(res,400,{error:'Medication name, dosage and frequency are required'});const patientId=b.patient_id||'demo-patient';const id=randomUUID();db.prepare(`INSERT INTO medications(id,patient_id,clinician_id,name,dosage,frequency,scheduled_time,instructions,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,patientId,u.role==='clinician'?u.id:(b.clinician_id||'demo-clinician'),b.name,b.dosage,b.frequency,b.scheduled_time||'',b.instructions||'',1,new Date().toISOString());const patient=db.prepare(`SELECT profile_id FROM patients WHERE id=?`).get(patientId);notifyCareTeam(patientId,'medication','Medication prescribed',`Your clinician prescribed ${b.name}.`,patientId);return send(res,201,db.prepare(`SELECT * FROM medications WHERE id=?`).get(id))}
    const medMatch=url.pathname.match(/^\/api\/medications\/([^/]+)$/);
    if(medMatch&&req.method==='PATCH'){const u=requireAuth(req,res,['clinician','caregiver','admin']);if(!u)return;const b=await body(req);const med=db.prepare(`SELECT * FROM medications WHERE id=?`).get(medMatch[1]);if(!med)return send(res,404,{error:'Medication not found'});if(u.role==='caregiver'){if(!b.mark_taken)return send(res,403,{error:'Caregivers can only mark prescribed medication as taken'});db.prepare(`UPDATE medications SET taken_at=?,taken_by=? WHERE id=?`).run(new Date().toISOString(),u.id,medMatch[1]);notify(med.clinician_id,'medication','Medication taken',`${med.name} was marked as taken by the caregiver.`,med.patient_id);return send(res,200,db.prepare(`SELECT * FROM medications WHERE id=?`).get(medMatch[1]))}const fields=['name','dosage','frequency','scheduled_time','instructions','active'];const set=fields.filter(k=>b[k]!==undefined).map(k=>`${k}=?`);const vals=fields.filter(k=>b[k]!==undefined).map(k=>k==='active'?(b[k]?1:0):b[k]);if(set.length)db.prepare(`UPDATE medications SET ${set.join(',')} WHERE id=?`).run(...vals,medMatch[1]);notifyCareTeam(med.patient_id,'medication','Medication updated',`Your clinician updated ${b.name||med.name}.`);return send(res,200,db.prepare(`SELECT * FROM medications WHERE id=?`).get(medMatch[1]))}
    if(url.pathname==='/api/appointments'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const patientId=url.searchParams.get('patient_id')||'demo-patient';return send(res,200,db.prepare(`SELECT * FROM appointments WHERE patient_id=? ORDER BY appointment_date,appointment_time`).all(patientId).map(x=>({...x,caregiver_confirmed:!!x.caregiver_confirmed})))}
    const apptMatch=url.pathname.match(/^\/api\/appointments\/([^/]+)$/);if(apptMatch&&req.method==='PATCH'){const u=requireAuth(req,res,['caregiver','clinician','admin']);if(!u)return;const b=await body(req);const ap=db.prepare(`SELECT * FROM appointments WHERE id=?`).get(apptMatch[1]);if(!ap)return send(res,404,{error:'Appointment not found'});if(u.role==='caregiver'){if(!b.confirm_presence)return send(res,403,{error:'Invalid confirmation'});db.prepare(`UPDATE appointments SET caregiver_confirmed=1,caregiver_confirmed_at=?,caregiver_confirmed_by=? WHERE id=?`).run(new Date().toISOString(),u.id,ap.id);notify(ap.clinician_id,'appointment','Appointment presence confirmed',`Caregiver confirmed attendance for the ${ap.appointment_type} on ${ap.appointment_date} at ${ap.appointment_time}.`,ap.patient_id)}else if(b.status)db.prepare(`UPDATE appointments SET status=? WHERE id=?`).run(b.status,ap.id);return send(res,200,{...db.prepare(`SELECT * FROM appointments WHERE id=?`).get(ap.id),caregiver_confirmed:!!db.prepare(`SELECT caregiver_confirmed FROM appointments WHERE id=?`).get(ap.id).caregiver_confirmed})}
    if(url.pathname==='/api/admin/access-monitor'&&req.method==='GET'){const u=requireAuth(req,res,['admin']);if(!u)return;const rows=db.prepare(`SELECT ca.*,pp.full_name patient_name,cp.full_name caregiver_name FROM caregiver_access ca JOIN patients p ON p.id=ca.patient_id JOIN profiles pp ON pp.id=p.profile_id JOIN profiles cp ON cp.id=ca.caregiver_id ORDER BY ca.expires_at`).all().map(x=>({...x,can_view_care_plan:!!x.can_view_care_plan,can_view_medications:!!x.can_view_medications,can_view_tasks:!!x.can_view_tasks,can_view_appointments:!!x.can_view_appointments,can_report_concerns:!!x.can_report_concerns}));const events=db.prepare(`SELECT ae.*,pp.full_name patient_name,cp.full_name caregiver_name FROM access_events ae LEFT JOIN patients pte ON pte.id=ae.patient_id LEFT JOIN profiles pp ON pp.id=pte.profile_id LEFT JOIN profiles cp ON cp.id=ae.caregiver_id ORDER BY ae.created_at DESC LIMIT 50`).all();return send(res,200,{consents:rows,events})}

    if(url.pathname==='/api/personal-record'&&req.method==='GET'){const u=requireAuth(req,res,['clinician']);if(!u)return;const pid=url.searchParams.get('patient_id')||'demo-patient';return send(res,200,db.prepare(`SELECT pr.*,p.profile_id,prof.full_name AS patient_name FROM personal_records pr JOIN patients p ON p.id=pr.patient_id JOIN profiles prof ON prof.id=p.profile_id WHERE pr.patient_id=?`).get(pid)||null)}
    if(url.pathname==='/api/personal-record'&&req.method==='PUT'){const u=requireAuth(req,res,['clinician']);if(!u)return;const b=await body(req);const pid=b.patient_id||'demo-patient';const patient=db.prepare(`SELECT prof.full_name AS patient_name FROM patients p JOIN profiles prof ON prof.id=p.profile_id WHERE p.id=?`).get(pid);if(!patient)return send(res,404,{error:'Patient not found'});const now=new Date().toISOString();db.prepare(`INSERT INTO personal_records(patient_id,full_name,date_of_birth,phone,email,address,emergency_contact_name,emergency_contact_phone,relationship,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(patient_id) DO UPDATE SET full_name=excluded.full_name,date_of_birth=excluded.date_of_birth,phone=excluded.phone,email=excluded.email,address=excluded.address,emergency_contact_name=excluded.emergency_contact_name,emergency_contact_phone=excluded.emergency_contact_phone,relationship=excluded.relationship,updated_by=excluded.updated_by,updated_at=excluded.updated_at`).run(pid,patient.patient_name,b.date_of_birth||'',b.phone||'',b.email||'',b.address||'',b.emergency_contact_name||'',b.emergency_contact_phone||'',b.relationship||'',u.id,now);return send(res,200,db.prepare(`SELECT pr.*,prof.full_name AS patient_name FROM personal_records pr JOIN patients p ON p.id=pr.patient_id JOIN profiles prof ON prof.id=p.profile_id WHERE pr.patient_id=?`).get(pid))}
    if(url.pathname==='/api/health-profile'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const pid=url.searchParams.get('patient_id')||'demo-patient';if(u.role!=='clinician')return send(res,403,{error:'Health profile is clinician-only'});return send(res,200,db.prepare(`SELECT * FROM health_profiles WHERE patient_id=?`).get(pid)||null)}
    if(url.pathname==='/api/health-profile'&&req.method==='PUT'){const u=requireAuth(req,res,['clinician']);if(!u)return;const b=await body(req);const pid=b.patient_id||'demo-patient';const fields=['blood_group','medicine_allergies','diabetes','chronic_illnesses','previous_conditions','surgical_history','obstetric_history','current_health_notes'];const vals=fields.map(k=>b[k]??'');db.prepare(`INSERT INTO health_profiles(patient_id,blood_group,medicine_allergies,diabetes,chronic_illnesses,previous_conditions,surgical_history,obstetric_history,current_health_notes,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(patient_id) DO UPDATE SET blood_group=excluded.blood_group,medicine_allergies=excluded.medicine_allergies,diabetes=excluded.diabetes,chronic_illnesses=excluded.chronic_illnesses,previous_conditions=excluded.previous_conditions,surgical_history=excluded.surgical_history,obstetric_history=excluded.obstetric_history,current_health_notes=excluded.current_health_notes,updated_by=excluded.updated_by,updated_at=excluded.updated_at`).run(pid,...vals,u.id,new Date().toISOString());return send(res,200,db.prepare(`SELECT * FROM health_profiles WHERE patient_id=?`).get(pid))}
    if(url.pathname==='/api/vaccinations'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const pid=url.searchParams.get('patient_id')||'demo-patient';if(u.role==='caregiver'){const a=db.prepare(`SELECT 1 FROM caregiver_access WHERE patient_id=? AND caregiver_id=? AND status='active' AND (expires_at IS NULL OR expires_at>?)`).get(pid,u.id,new Date().toISOString());if(!a)return send(res,403,{error:'Caregiver access is not active'});}return send(res,200,db.prepare(`SELECT * FROM vaccinations WHERE patient_id=? ORDER BY administered_date DESC`).all(pid))}
    if(url.pathname==='/api/vaccinations'&&req.method==='POST'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);if(!b.vaccine_name)return send(res,400,{error:'Vaccine name is required'});const id=randomUUID();db.prepare(`INSERT INTO vaccinations(id,patient_id,vaccine_name,dose,administered_date,next_due_date,status,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,b.patient_id||'demo-patient',b.vaccine_name,b.dose||'',b.administered_date||'',b.next_due_date||'',b.status||'completed',b.notes||'',u.id,new Date().toISOString());notifyCareTeam(b.patient_id||'demo-patient','vaccination','Vaccination record updated',`A vaccination record for ${b.vaccine_name} was added.`,b.patient_id||'demo-patient');return send(res,201,db.prepare(`SELECT * FROM vaccinations WHERE id=?`).get(id))}
    if(url.pathname==='/api/pregnancy-scans'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const pid=url.searchParams.get('patient_id')||'demo-patient';if(u.role==='caregiver'){const a=db.prepare(`SELECT 1 FROM caregiver_access WHERE patient_id=? AND caregiver_id=? AND status='active' AND (expires_at IS NULL OR expires_at>?)`).get(pid,u.id,new Date().toISOString());if(!a)return send(res,403,{error:'Caregiver access is not active'});}return send(res,200,db.prepare(`SELECT * FROM pregnancy_scans WHERE patient_id=? ORDER BY scan_date DESC`).all(pid))}
    if(url.pathname==='/api/pregnancy-scans'&&req.method==='POST'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);if(!b.scan_type)return send(res,400,{error:'Scan type is required'});const id=randomUUID();db.prepare(`INSERT INTO pregnancy_scans(id,patient_id,scan_type,scan_date,gestational_week,findings,clinician_notes,file_reference,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,b.patient_id||'demo-patient',b.scan_type,b.scan_date||'',b.gestational_week?Number(b.gestational_week):null,b.findings||'',b.clinician_notes||'',b.file_reference||'',b.status||'available',u.id,new Date().toISOString());notifyCareTeam(b.patient_id||'demo-patient','scan','Pregnancy scan added',`${b.scan_type} has been added to the shared pregnancy record.`,b.patient_id||'demo-patient');return send(res,201,db.prepare(`SELECT * FROM pregnancy_scans WHERE id=?`).get(id))}
    if(url.pathname==='/api/availability'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const cid=url.searchParams.get('clinician_id')||u.id;return send(res,200,db.prepare(`SELECT * FROM clinician_availability WHERE clinician_id=? AND status='available' ORDER BY availability_date,start_time`).all(cid))}
    if(url.pathname==='/api/availability'&&req.method==='POST'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);if(!b.availability_date||!b.start_time||!b.end_time)return send(res,400,{error:'Date and availability window are required'});const id=randomUUID();db.prepare(`INSERT INTO clinician_availability(id,clinician_id,availability_date,start_time,end_time,slot_minutes,status,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,u.role==='clinician'?u.id:(b.clinician_id||u.id),b.availability_date,b.start_time,b.end_time,Number(b.slot_minutes||30),'available',new Date().toISOString());return send(res,201,db.prepare(`SELECT * FROM clinician_availability WHERE id=?`).get(id))}
    if(url.pathname==='/api/appointments'&&req.method==='POST'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);const cid=u.role==='clinician'?u.id:b.clinician_id;if(!b.patient_id||!b.appointment_date||!b.appointment_time||!b.appointment_type)return send(res,400,{error:'Patient, date, time and appointment type are required'});const slot=db.prepare(`SELECT * FROM clinician_availability WHERE clinician_id=? AND availability_date=? AND start_time<=? AND end_time>? AND status='available'`).get(cid,b.appointment_date,b.appointment_time,b.appointment_time);if(!slot)return send(res,409,{error:'Selected time is outside the clinician availability'});const clash=db.prepare(`SELECT id FROM appointments WHERE clinician_id=? AND appointment_date=? AND appointment_time=? AND status IN ('scheduled','reschedule_pending')`).get(cid,b.appointment_date,b.appointment_time);if(clash)return send(res,409,{error:'That time slot is already booked'});const id=randomUUID();db.prepare(`INSERT INTO appointments(id,patient_id,clinician_id,appointment_date,appointment_time,appointment_type,location,status,notes) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,b.patient_id,cid,b.appointment_date,b.appointment_time,b.appointment_type,b.location||'', 'scheduled',b.notes||'');notifyCareTeam(b.patient_id,'appointment','Appointment scheduled',`A new ${b.appointment_type} appointment was scheduled for ${b.appointment_date} at ${b.appointment_time}.`,b.patient_id);return send(res,201,db.prepare(`SELECT * FROM appointments WHERE id=?`).get(id))}
    if(url.pathname==='/api/reschedule-requests'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const q=u.role==='clinician'?db.prepare(`SELECT r.*,a.patient_id,a.clinician_id,a.appointment_date,a.appointment_time,p.full_name patient_name FROM appointment_reschedule_requests r JOIN appointments a ON a.id=r.appointment_id JOIN patients pt ON pt.id=a.patient_id JOIN profiles p ON p.id=pt.profile_id WHERE a.clinician_id=? ORDER BY r.created_at DESC`).all(u.id):db.prepare(`SELECT r.*,a.patient_id,a.clinician_id,a.appointment_date,a.appointment_time FROM appointment_reschedule_requests r JOIN appointments a ON a.id=r.appointment_id WHERE a.patient_id='demo-patient' ORDER BY r.created_at DESC`).all();return send(res,200,q)}
    if(url.pathname==='/api/reschedule-requests'&&req.method==='POST'){const u=requireAuth(req,res,['caregiver']);if(!u)return;const b=await body(req);if(!b.appointment_id)return send(res,400,{error:'Appointment is required'});const ap=db.prepare(`SELECT * FROM appointments WHERE id=?`).get(b.appointment_id);if(!ap)return send(res,404,{error:'Appointment not found'});const id=randomUUID();db.prepare(`INSERT INTO appointment_reschedule_requests(id,appointment_id,requested_by,requested_date,requested_time,reason,created_at) VALUES(?,?,?,?,?,?,?)`).run(id,ap.id,u.id,b.requested_date||'',b.requested_time||'',b.reason||'',new Date().toISOString());db.prepare(`UPDATE appointments SET status='reschedule_pending' WHERE id=?`).run(ap.id);notify(ap.clinician_id,'appointment','Reschedule requested',`A caregiver requested a change to the ${ap.appointment_type} appointment.`,ap.patient_id);return send(res,201,db.prepare(`SELECT * FROM appointment_reschedule_requests WHERE id=?`).get(id))}
    const rr=url.pathname.match(/^\/api\/reschedule-requests\/([^/]+)$/);if(rr&&req.method==='PATCH'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);const r=db.prepare(`SELECT * FROM appointment_reschedule_requests WHERE id=?`).get(rr[1]);if(!r)return send(res,404,{error:'Request not found'});const ap=db.prepare(`SELECT * FROM appointments WHERE id=?`).get(r.appointment_id);if(b.status==='approved'){const nd=r.requested_date||ap.appointment_date,nt=r.requested_time||ap.appointment_time;const slot=db.prepare(`SELECT 1 FROM clinician_availability WHERE clinician_id=? AND availability_date=? AND start_time<=? AND end_time>? AND status='available'`).get(ap.clinician_id,nd,nt,nt);if(!slot)return send(res,409,{error:'Requested reschedule time is outside clinician availability'});const clash=db.prepare(`SELECT id FROM appointments WHERE clinician_id=? AND appointment_date=? AND appointment_time=? AND id<>? AND status IN ('scheduled','reschedule_pending')`).get(ap.clinician_id,nd,nt,ap.id);if(clash)return send(res,409,{error:'Requested reschedule time is already booked'});db.prepare(`UPDATE appointments SET appointment_date=?,appointment_time=?,status='scheduled',caregiver_confirmed=0,caregiver_confirmed_at=NULL,caregiver_confirmed_by=NULL WHERE id=?`).run(nd,nt,ap.id)}else if(b.status==='rejected')db.prepare(`UPDATE appointments SET status='scheduled' WHERE id=?`).run(ap.id);db.prepare(`UPDATE appointment_reschedule_requests SET status=?,reviewed_by=?,reviewed_at=? WHERE id=?`).run(b.status,u.id,new Date().toISOString(),r.id);notifyCareTeam(ap.patient_id,'appointment',`Reschedule ${b.status}`,`The appointment reschedule request was ${b.status}.`,ap.patient_id);return send(res,200,db.prepare(`SELECT * FROM appointment_reschedule_requests WHERE id=?`).get(r.id))}
    if(url.pathname==='/api/access'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const row=db.prepare(`SELECT * FROM caregiver_access WHERE patient_id='demo-patient' AND caregiver_id='demo-caregiver'`).get();return send(res,200,bools(row,['can_view_care_plan','can_view_medications','can_view_tasks','can_view_appointments','can_view_financials','can_report_concerns']))}
    if(url.pathname==='/api/access'&&req.method==='PUT'){
      const u=requireAuth(req,res,['patient','admin']); if(!u)return;
      const b=await body(req);
      const fields=['can_view_care_plan','can_view_medications','can_view_tasks','can_view_appointments','can_report_concerns','status','expires_at'];
      const set=fields.filter(k=>b[k]!==undefined).map(k=>`${k}=?`);
      const vals=fields.filter(k=>b[k]!==undefined).map(k=>typeof b[k]==='boolean'?(b[k]?1:0):b[k]);
      if(set.length)db.prepare(`UPDATE caregiver_access SET ${set.join(',')} WHERE id='ca1'`).run(...vals);
      const row=db.prepare(`SELECT * FROM caregiver_access WHERE id='ca1'`).get();
      db.prepare(`INSERT INTO access_events(id,actor_id,patient_id,caregiver_id,action,detail,created_at) VALUES(?,?,?,?,?,?,?)`).run(randomUUID(),u.id,row.patient_id,row.caregiver_id,'consent_updated','Caregiver access permissions were updated.',new Date().toISOString());
      return send(res,200,bools(row,['can_view_care_plan','can_view_medications','can_view_tasks','can_view_appointments','can_view_financials','can_report_concerns']));
    }

    if(url.pathname==='/api/tasks'&&req.method==='POST'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const b=await body(req);if(!b.patient_id||!b.title)return send(res,400,{error:'Patient and task title are required'});const id=randomUUID();const assigned=b.assigned_to||'demo-caregiver';db.prepare(`INSERT INTO tasks(id,patient_id,assigned_to,created_by,title,description,priority,status,due_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,b.patient_id,assigned,u.id,b.title,b.description||'',b.priority||'normal','pending',b.due_at||'');notify(assigned,'task','New care task assigned',`A clinician assigned you: ${b.title}.`,b.patient_id);return send(res,201,db.prepare(`SELECT * FROM tasks WHERE id=?`).get(id))}
    if(url.pathname==='/api/tasks'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;const pid=url.searchParams.get('patient_id')||'demo-patient';return send(res,200,db.prepare(`SELECT * FROM tasks WHERE patient_id=? ORDER BY id`).all(pid))}
    const taskMatch=url.pathname.match(/^\/api\/tasks\/([^/]+)$/);if(taskMatch&&req.method==='PATCH'){const u=requireAuth(req,res,['caregiver','clinician','admin']);if(!u)return;const b=await body(req);db.prepare(`UPDATE tasks SET status=?,completed_at=? WHERE id=?`).run(b.completed?'completed':'pending',b.completed?new Date().toISOString():null,taskMatch[1]);const t=db.prepare(`SELECT * FROM tasks WHERE id=?`).get(taskMatch[1]);if(t)notify(t.created_by,'task','Care task updated',`${t.title} was marked ${b.completed?'completed':'pending'}.`,t.patient_id);return send(res,200,t)}
    if(url.pathname==='/api/alerts'&&req.method==='GET'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;const rows=db.prepare(`SELECT a.*,p.full_name patient_name FROM alerts a JOIN patients pt ON pt.id=a.patient_id JOIN profiles p ON p.id=pt.profile_id WHERE a.assigned_clinician_id=? ORDER BY a.created_at DESC`).all(u.role==='clinician'?u.id:'demo-clinician');return send(res,200,rows)}
    if(url.pathname==='/api/alerts'&&req.method==='POST'){const u=requireAuth(req,res,['caregiver','clinician','admin']);if(!u)return;return send(res,201,createAlert(await body(req),u))}
    const alertMatch=url.pathname.match(/^\/api\/alerts\/([^/]+)\/ack$/);if(alertMatch&&req.method==='PATCH'){const u=requireAuth(req,res,['clinician','admin']);if(!u)return;db.prepare(`UPDATE alerts SET status='acknowledged',acknowledged_by=?,acknowledged_at=? WHERE id=?`).run(u.id,new Date().toISOString(),alertMatch[1]);return send(res,200,{ok:true})}
    if(url.pathname==='/api/notifications'&&req.method==='GET'){const u=requireAuth(req,res);if(!u)return;return send(res,200,db.prepare(`SELECT * FROM notifications WHERE recipient_id=? ORDER BY created_at DESC LIMIT 50`).all(u.id))}
    if(url.pathname==='/api/notifications/read-all'&&req.method==='POST'){const u=requireAuth(req,res);if(!u)return;db.prepare(`UPDATE notifications SET read_at=? WHERE recipient_id=? AND read_at IS NULL`).run(new Date().toISOString(),u.id);return send(res,200,{ok:true})}
    return send(res,404,{error:'Not found'});
  } catch(e){console.error(e);return send(res,500,{error:e.message||'Server error'})}
});
const PORT=Number(process.env.PORT||3001);
server.on('error',e=>{console.error(e);process.exitCode=1});
server.listen(PORT,()=>console.log(`CareBridge SQLite API running at http://localhost:${PORT}`));
