import{useEffect,useState}from'react';
import{useParams}from'react-router-dom';
import Shell from'../../components/layout/Shell';import Card from'../../components/ui/Card';import Badge from'../../components/ui/Badge';import Button from'../../components/ui/Button';
import{getVaccinations,addVaccination,getPregnancyScans,addPregnancyScan,getHealthProfile,saveHealthProfile,getPersonalRecord,savePersonalRecord}from'../../services/data';import{Syringe,ScanLine,LockKeyhole,Plus,Save}from'lucide-react';

export default function MaternityRecords({role}:{role:'patient'|'caregiver'|'clinician'}){
 const{ id }=useParams(); const patientId=id||'demo-patient';
 const[vaccines,setVaccines]=useState<any[]>([]),[scans,setScans]=useState<any[]>([]),[health,setHealth]=useState<any>(null),[personal,setPersonal]=useState<any>(null),[showV,setShowV]=useState(false),[showS,setShowS]=useState(false);
 const load=async()=>{setVaccines(await getVaccinations(patientId));setScans(await getPregnancyScans(patientId));if(role==='clinician'){setHealth(await getHealthProfile(patientId));setPersonal(await getPersonalRecord(patientId))}};
 useEffect(()=>{load()},[]);
 return <Shell role={role} name={role==='clinician'?'Dr. Meera Rao':role==='patient'?'Lakshmi Rao':'Anita Kumar'}><div className="max-w-7xl mx-auto p-5 md:p-8"><p className="text-sm font-semibold text-brand-700">Maternity records</p><h1 className="text-3xl font-bold">{role==='clinician'?'Clinical & pregnancy records':'Pregnancy records'}</h1><p className="text-slate-500 mt-1">{role==='clinician'?'Private health history plus shared pregnancy records.':'Vaccination and scan information shared with your care team.'}</p>
 {role==='clinician'&&<><PersonalRecord record={personal} setRecord={setPersonal} patientId={patientId}/><HealthProfile health={health} setHealth={setHealth} patientId={patientId}/></>} 
 <div className="grid lg:grid-cols-2 gap-5 mt-6"><Card className="p-6"><div className="flex justify-between items-center"><div className="flex gap-3 items-center"><div className="p-2.5 rounded-xl bg-brand-50 text-brand-700"><Syringe/></div><div><h2 className="font-bold">Vaccinations</h2><p className="text-xs text-slate-400">Shared maternity vaccination record</p></div></div>{role==='clinician'&&<Button variant="secondary" onClick={()=>setShowV(!showV)}><Plus size={16}/> Add</Button>}</div>{showV&&<VaccineForm patientId={patientId} onDone={async()=>{setShowV(false);setVaccines(await getVaccinations(patientId))}}/>}<div className="space-y-3 mt-5">{vaccines.map(v=><div className="border rounded-xl p-4" key={v.id}><div className="flex justify-between"><b>{v.vaccine_name}</b><Badge tone={v.status==='completed'?'success':'warning'}>{v.status}</Badge></div><p className="text-xs text-slate-500 mt-1">{v.dose||'Dose'} · {v.administered_date||'Date not recorded'}{v.next_due_date?` · Next due ${v.next_due_date}`:''}</p>{v.notes&&<p className="text-xs text-slate-400 mt-2">{v.notes}</p>}</div>)}{!vaccines.length&&<p className="text-sm text-slate-400">No vaccination records yet.</p>}</div></Card>
 <Card className="p-6"><div className="flex justify-between items-center"><div className="flex gap-3 items-center"><div className="p-2.5 rounded-xl bg-brand-50 text-brand-700"><ScanLine/></div><div><h2 className="font-bold">Pregnancy scans</h2><p className="text-xs text-slate-400">Shared scan records and findings</p></div></div>{role==='clinician'&&<Button variant="secondary" onClick={()=>setShowS(!showS)}><Plus size={16}/> Add</Button>}</div>{showS&&<ScanForm patientId={patientId} onDone={async()=>{setShowS(false);setScans(await getPregnancyScans(patientId))}}/>}<div className="space-y-3 mt-5">{scans.map(s=><div className="border rounded-xl p-4" key={s.id}><div className="flex justify-between"><b>{s.scan_type}</b><Badge tone="success">{s.status}</Badge></div><p className="text-xs text-slate-500 mt-1">{s.scan_date||'Date not recorded'}{s.gestational_week?` · ${s.gestational_week} weeks`:''}</p><p className="text-sm text-slate-600 mt-3">{s.findings||'Findings recorded in the clinical report.'}</p>{s.clinician_notes&&<p className="text-xs text-slate-400 mt-2">Clinician note: {s.clinician_notes}</p>}{s.file_reference&&<p className="text-xs text-brand-700 mt-2">Report reference: {s.file_reference}</p>}</div>)}{!scans.length&&<p className="text-sm text-slate-400">No scan records yet.</p>}</div></Card></div></div></Shell>
}
function PersonalRecord({record,setRecord,patientId}:{record:any;setRecord:(x:any)=>void;patientId:string}){const[saving,setSaving]=useState(false);if(!record)return <Card className="mt-6 p-6">Loading personal record…</Card>;const f=(k:string,label:string,type='text')=><label className="text-sm font-medium">{label}<input type={type} className="field mt-1" value={record[k]||''} onChange={e=>setRecord({...record,[k]:e.target.value})}/></label>;return <Card className="mt-6 p-6 border-slate-200"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-700">Personal records</p><h2 className="text-xl font-bold mt-1">{record.patient_name||record.full_name}</h2><p className="text-xs text-slate-400 mt-1">Clinician-only identification and contact record for this patient.</p></div><Badge tone="success">{record.patient_name||'Patient'}</Badge></div><div className="grid md:grid-cols-2 gap-4 mt-5">{f('date_of_birth','Date of birth','date')}{f('phone','Phone')}{f('email','Email')}{f('relationship','Emergency contact relationship')}{f('emergency_contact_name','Emergency contact name')}{f('emergency_contact_phone','Emergency contact phone')}<label className="text-sm font-medium md:col-span-2">Address<textarea rows={2} className="field mt-1" value={record.address||''} onChange={e=>setRecord({...record,address:e.target.value})}/></label></div><Button loading={saving} className="mt-5" onClick={async()=>{setSaving(true);try{setRecord(await savePersonalRecord({...record,patient_id:patientId}))}finally{setSaving(false)}}}><Save size={16}/> Save personal record</Button></Card>}
function HealthProfile({health,setHealth,patientId}:{health:any;setHealth:(x:any)=>void;patientId:string}){const[saving,setSaving]=useState(false);if(!health)return <Card className="mt-6 p-6">Loading private health profile…</Card>;const f=(k:string,label:string)=><label className="text-sm font-medium">{label}<textarea rows={2} className="field mt-1" value={health[k]||''} onChange={e=>setHealth({...health,[k]:e.target.value})}/></label>;return <Card className="mt-6 p-6 border-brand-100"><div className="flex items-center gap-3"><LockKeyhole className="text-brand-700"/><div><h2 className="font-bold">Private health profile</h2><p className="text-xs text-slate-400">Clinician-only. Used to guide clinical assessment and care planning.</p></div></div><div className="grid md:grid-cols-2 gap-4 mt-5"><label className="text-sm font-medium">Blood group<input className="field mt-1" value={health.blood_group||''} onChange={e=>setHealth({...health,blood_group:e.target.value})}/></label>{f('medicine_allergies','Medicine allergies')}{f('diabetes','Diabetes / glucose history')}{f('chronic_illnesses','Other chronic illnesses')}{f('previous_conditions','Previous medical conditions')}{f('surgical_history','Surgical history')}{f('obstetric_history','Obstetric history')}{f('current_health_notes','Current health notes')}</div><Button loading={saving} className="mt-5" onClick={async()=>{setSaving(true);try{setHealth(await saveHealthProfile({...health,patient_id:patientId}))}finally{setSaving(false)}}}><Save size={16}/> Save private profile</Button></Card>}
function VaccineForm({patientId,onDone}:{patientId:string;onDone:()=>void}){const[f,setF]=useState<any>({vaccine_name:'',dose:'',administered_date:'',next_due_date:'',status:'completed',notes:''});return <div className="mt-5 p-4 bg-slate-50 rounded-xl grid md:grid-cols-2 gap-3"><input placeholder="Vaccine name" className="field" value={f.vaccine_name} onChange={e=>setF({...f,vaccine_name:e.target.value})}/><input placeholder="Dose" className="field" value={f.dose} onChange={e=>setF({...f,dose:e.target.value})}/><input type="date" className="field" value={f.administered_date} onChange={e=>setF({...f,administered_date:e.target.value})}/><input type="date" className="field" value={f.next_due_date} onChange={e=>setF({...f,next_due_date:e.target.value})}/><textarea placeholder="Notes" className="field md:col-span-2" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><Button onClick={async()=>{await addVaccination({...f,patient_id:patientId});onDone()}}>Save vaccination</Button></div>}
function ScanForm({patientId,onDone}:{patientId:string;onDone:()=>void}){const[f,setF]=useState<any>({scan_type:'',scan_date:'',gestational_week:'',findings:'',clinician_notes:'',file_reference:''});return <div className="mt-5 p-4 bg-slate-50 rounded-xl grid md:grid-cols-2 gap-3"><input placeholder="Scan type (e.g. anomaly scan)" className="field" value={f.scan_type} onChange={e=>setF({...f,scan_type:e.target.value})}/><input type="date" className="field" value={f.scan_date} onChange={e=>setF({...f,scan_date:e.target.value})}/><input type="number" placeholder="Gestational week" className="field" value={f.gestational_week} onChange={e=>setF({...f,gestational_week:e.target.value})}/><input placeholder="Report/file reference" className="field" value={f.file_reference} onChange={e=>setF({...f,file_reference:e.target.value})}/><textarea placeholder="Findings / summary" className="field md:col-span-2" value={f.findings} onChange={e=>setF({...f,findings:e.target.value})}/><textarea placeholder="Clinician notes" className="field md:col-span-2" value={f.clinician_notes} onChange={e=>setF({...f,clinician_notes:e.target.value})}/><Button onClick={async()=>{await addPregnancyScan({...f,patient_id:patientId});onDone()}}>Save scan record</Button></div>}
